### PR TITLE
fix: Implement `importKey` , `exportKey` for platformAPI

### PR DESCRIPTION
**Pull request by tbrunain**
This PR contains : 

- [ ] Add `exportKey` function in PlatformAPI . (https://docs.ava.network/v1.0/en/api/platform/#platformexportkey)
- [ ] Add `importKey` function in PlatformAPI . (https://docs.ava.network/v1.0/en/api/platform/#platformimportkey)
- [ ] Add tests for those calls

### CODE REVIEW

**Comment by tbrunain** [comment]
Need to be sure that the code I implemented works, but it's too late for me start a new Gecko node with 0.5.3 today, that will be for tomorrow !

**Comment by tbrunain** [comment]
Tested on my local, I think it's ready for review now

**Comment by tbrunain** [comment]
Tested on my local, I think it's ready for review now

**Comment by tbrunain** [comment]
@collincusce oups indeed, I think I reverted them all now

**Comment by collincusce** [comment]
Looks good, I'm merging these into the user_changes branch to run all three with tests at the same time before moving to master.

**Comment by collincusce** [comment]
Orrr not because I forgot to rebase. Lovely. Well it worked out this time.

**Pull request merged**
