### PR TITLE
More updates to README

### PR DESCRIPTION
**Pull request by cgcardona**
Working through the docs and have some updates for the `Example 3 &mdash; Sending An Asset` section

* Add `await` keyword for async `makeUnsignedTx` call
* Replace nonexistent `amount` arg with `sendAmount` var
* Replace `makeUnsignedTx`'s 4th and 5th args with array of strings instead of array of buffers

### CODE REVIEW

**Comment by collincusce** [comment]
Fixed missing addressStrings variable. Everything else looks good.

**Comment by cgcardona** [comment]
I noticed that on line #135 `addressStrings` gets declared.

```js
let addressStrings = myKeychain.getAddressStrings(); //returns an array of strings for the addresses
```

I wasn't sure if it made sense to create it again right before the `makeUnsignedTx` call on line #322 or not.  The same should be true for the other PR as well.

**Comment by collincusce** [comment]
They're different tutorials.

**Comment by cgcardona** [comment]
Ah yes, good point. 👍

**Pull request merged**
